version: "3"
services:
  rabbitqueue:
    image: rabbitmq:3-management
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitnet
  sender:
    image: dockla/rabbit-sender
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "1337:1337"
    networks:
      - rabbitnet
  receiver:
    image: dockla/rabbit-receiver
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - rabbitnet
networks:
  rabbitnet:
