version: "3"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - rabbitnet
  rabbitqueue:
    image: rabbitmq:3-management
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "15672:15672"
#      - "5672:5672"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - rabbitnet
  sender:
    image: dockla/rabbit-sender:v1
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "1337:1337"
    networks:
      - rabbitnet
  receiver:
    image: dockla/rabbit-receiver:1sec
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - rabbitnet
networks:
  rabbitnet:
