apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: rabbitqueue
    name: rabbitqueue
  spec:
    replicas: 1 # tells deployment to run 1 pod matching the template
    selector:
      matchLabels:
        run: rabbitqueue
    template:
      metadata:
        labels:
          run: rabbitqueue
      spec:
        containers:
        - image: rabbitmq:3-management
          name: rabbitqueue
          ports:
          - containerPort: 15672
            protocol: TCP
        restartPolicy: Always
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: sender
    name: sender
  spec:
    replicas: 1 # You can scale the senders for fault tolerance
    selector:
      matchLabels:
        run: sender
    template:
      metadata:
        labels:
          run: sender
      spec:
        containers:
        - image: dockla/rabbit-sender:v1
          name: sender
          ports:
          - containerPort: 1337
            protocol: TCP
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: receiver
    name: receiver
  spec:
    replicas: 3 # You can scale the receivers to increase consumer speed
    selector:
      matchLabels:
        run: receiver
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          run: receiver
      spec:
        containers:
        - image: dockla/rabbit-receiver:1sec
          imagePullPolicy: IfNotPresent
          name: receiver
        restartPolicy: Always

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: rabbitqueue
    name: rabbitqueue
  spec:
    ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      run: rabbitqueue
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: rabbitqueue
    name: rabbitqueue-management-svc
  spec:
    ports:
    - nodePort: 31195
      port: 15672
      protocol: TCP
      targetPort: 15672
    selector:
      run: rabbitqueue
    sessionAffinity: None
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: sender
    name: sender-svc
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 31155
      port: 1337
      protocol: TCP
      targetPort: 1337
    selector:
      run: sender
    sessionAffinity: None
    type: NodePort
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
