apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:

############ Deployments ############
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: rabbitqueue
    labels:
      component: rabbitqueue
      app: rabbitlab
  spec:
    replicas: 1 # tells deployment to run 1 pod matching the template
    selector:
      matchLabels:
        component: rabbitqueue
    template:
      metadata:
        labels:
          component: rabbitqueue
      spec:
        containers:
        - image: rabbitmq:3-management
          name: rabbitqueue
          ports:
          - containerPort: 15672
            protocol: TCP
        restartPolicy: Always

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: sender
    labels:
      component: sender
      app: rabbitlab
  spec:
    replicas: 1 # You can scale the senders for fault tolerance
    selector:
      matchLabels:
        component: sender
    template:
      metadata:
        labels:
          component: sender
      spec:
        containers:
        - image: dockla/rabbit-sender:v1
          name: sender
          ports:
          - containerPort: 1337
            protocol: TCP

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: receiver
    labels:
      component: receiver
      app: rabbitlab
  spec:
    replicas: 3 # You can scale the receivers to increase consumer speed
    selector:
      matchLabels:
        component: receiver
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          component: receiver
      spec:
        containers:
        - image: dockla/rabbit-receiver:1sec
          imagePullPolicy: IfNotPresent
          name: receiver
        restartPolicy: Always

############ Services ###############
- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitqueue
    labels:
      component: rabbitqueue
      app: rabbitlab
  spec:
    ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      component: rabbitqueue
    type: ClusterIP # Should not be exposed outside of the Cluster

- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitqueue-management-svc
    labels:
      component: rabbitqueue
      app: rabbitlab
  spec:
    ports:
    - nodePort: 32000
      port: 15672
      targetPort: 15672
      protocol: TCP
    selector:
      component: rabbitqueue
    sessionAffinity: None
    type: NodePort

- apiVersion: v1
  kind: Service
  metadata:
    name: sender-svc
    labels:
      component: sender
      app: rabbitlab
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32100
      port: 1337
      targetPort: 1337
      protocol: TCP
    selector:
      component: sender
    sessionAffinity: None
    type: NodePort
